### ISSUE TITLE
How to uninstall module

### ISSUE THREAD

**Issue by pabloblazquez** [fballiano/openmage-category-sort-direction#1]
Hello Fabrizio,

I would like to uninstall your category sort direction module. It's working perfectly, the reason is other.
Can you put me in the right direction to uninstall it correctly, please?

Thanks a lot for your excellent work.

**Comment by fballiano** [comment]
you can simply remove the files you added, no big deal :)

**Comment by pabloblazquez** [comment]
Thanks for your reply. I'm learning Magento and I was not sure if I had to
do any extra actions al database level.

Thansk

2016-06-05 20:01 GMT+02:00 Fabrizio Balliano notifications@github.com:

> you can simply remove the files you added, no big deal :)
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/fballiano/magento-category-sort-direction/issues/1#issuecomment-223827452,
> or mute the thread
> https://github.com/notifications/unsubscribe/AFF5lmDtvIaYcz730G60c8HW53l-QFRoks5qIw7ygaJpZM4IuaCf
> .

##
